Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2022-11, with the labels that each got.

#43 Add support for testnet addresses starting with x
  index.html
  scripts/bitTrx.js
  scripts/settings.js
Labels: enhancement

#42 [Wallet] Add full WIF integrity checks
  index.html
  scripts/wallet.js
Labels: enhancement

#45 Include fee calculation while choosing UTXOs
  index.html
Labels: bug, enhancement

#46 Improved ledger address confirmation and added confirm popups
  assets/style/style.css
  index.html
  scripts/misc.js
  scripts/wallet.js
Labels: enhancement, Mid Priority (~405 PIV)

#47 [Crypto] Updated Noble + switched signatures
  index.html
  scripts/bitTrx.js
  scripts/libs/ellipticcurve.js
  scripts/libs/noble-secp256k1.js
  scripts/libs/secp256k1.js
  scripts/misc.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
Labels: enhancement

#48 [Trivial] Standardised functions
  scripts/libs/aes-gcm.js
  scripts/libs/script.js
  scripts/misc.js
  scripts/network.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
Labels: enhancement

#57 Fix long transactions not sending properly
  scripts/network.js
Labels: bug, Minor (~45 PIV)

#49 Masternode and Governance
  index.html
  scripts/masternode.js
  scripts/misc.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: enhancement, High Priority (>1200 PIV)

#38 Use CHECKCOLDSTAKEVERIFY_LOF for coldstakingoutput
  index.html
  scripts/bitTrx.js
Labels: bug, enhancement, Mid Priority (~405 PIV)

#63 Fix Undelegation
  index.html
  scripts/network.js
Labels: bug, enhancement, Mid Priority (~405 PIV)

#62 Adding mempool
  index.html
  scripts/masternode.js
  scripts/mempool.js
  scripts/misc.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: enhancement, High Priority (>1200 PIV)

#39 I18n Addon
  index.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/i18n.js
  scripts/misc.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: enhancement, High Priority (>1200 PIV)

#66 add locales dir to dockerfile
  docker/Dockerfile
Labels: bug
