Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2022-10, with the labels that each got.

#28 Basic 'Testnet Mode'
  index.html
  scripts/bitTrx.js
  scripts/settings.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
Labels: enhancement

#27 Stake Rewards List
  assets/style/style.css
  index.html
  scripts/network.js
Labels: enhancement

#29 Added the ability to import and export the ciphered private key
  assets/style/style.css
  index.html
  scripts/misc.js
  scripts/wallet.js
Labels: enhancement

#31 Added ledger support
  index.html
  scripts/bitTrx.js
  scripts/libs/ledger.js
  scripts/network.js
  scripts/wallet.js
Labels: enhancement

#36 Add HD + bip39 seed phrase support
  assets/style/style.css
  index.html
  scripts/bitTrx.js
  scripts/libs/bip39.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: enhancement, High Priority (>1200 PIV)

#41 [UI] Seed Phrase import + input improvement
  assets/style/style.css
  index.html
  scripts/wallet.js
Labels: enhancement

#40 Fixed code rebase duplication mistake
  index.html
Labels: bug
