Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-07, with the labels that each got.

#148 New Landing (+ Loading Screen)
  assets/img_governance.png
  assets/img_pos.png
  assets/img_privacy.png
  assets/img_slider_bars.png
  changelog.md
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
Labels: enhancement

#145 New 'Governance' page
  assets/style/style.css
  index.template.html
  scripts/database.js
  scripts/flipdown.js
  scripts/global.js
  scripts/index.js
  scripts/masternode.js
  scripts/settings.js
Labels: enhancement

#151 Fix password modal on front
  index.template.html
Labels: bug

#150 Improve Mnemonic + Password handling security
  scripts/global.js
  scripts/wallet.js
Labels: bug, enhancement

#152 Testnet toggler now follows network state
  index.template.html
  scripts/global.js
  scripts/settings.js
Labels: bug

#153 Run npm audit fix
  package-lock.json
Labels: enhancement

#149 Add tor masternodes
  package-lock.json
  package.json
  scripts/global.js
  scripts/masternode.js
  webpack.common.js
Labels: enhancement

#154 Fix long UTXO sync on wallet import
  scripts/wallet.js
Labels: bug

#159 Centre Align modals + Add modern X button to one
  index.template.html
Labels: bug, enhancement
