Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-08, with the labels that each got.

#160 Update translation tags, add Portuguese + Brazilian
  index.template.html
  locale/en/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/changelog.js
  scripts/charting.js
  scripts/database.js
  scripts/flipdown.js
  scripts/global.js
  scripts/i18n.js
  scripts/masternode.js
  scripts/misc.js
  scripts/native.js
  scripts/network.js
  scripts/promos.js
  scripts/settings.js
  scripts/transactions.js
  scripts/wallet.js
Labels: enhancement

#163 Add CSV exports & massively improve scaling
  index.template.html
  scripts/index.js
  scripts/misc.js
  scripts/promos.js
Labels: enhancement

#164 Integrate 🇵🇭 to the i18n system (by Clover)
  locale/ph/translation.js
  scripts/i18n.js
Labels: enhancement

#168 Governance UI Improvements
  assets/style/style.css
  locale/en/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/masternode.js
Labels: bug, enhancement

#170 Fix openExplorer() bugs
  scripts/global.js
Labels: bug

#169 Add Balance Decimals slider setting
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/misc.js
  scripts/settings.js
Labels: enhancement

#173 Add German translations
  locale/de/translation.js
  scripts/i18n.js
Labels: enhancement

#171 Bump to v1.1.0 + Compile Changelog
  changelog.md
  package-lock.json
  package.json
Labels: documentation

#174 v1.1.0 Changelog Finalised
  changelog.md
Labels: documentation

#175 Move flags to the end of the footer
  locale/de/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
Labels: enhancement

#178 Fix deleteProposal() and missing PaymentAddress
  scripts/global.js
Labels: Bug, Awaiting Review, Review Reward: 50 PIV

#179 Add Testing section to PR description
  .github/pull_request_template.md
Labels: Documentation, Awaiting Review

#177 Add "Change Password" functionality
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#180 Fix + Improve Debug Mode
  scripts/global.js
  scripts/mempool.js
  scripts/transactions.js
Labels: Bug, Enhancement, Awaiting Review, Review Reward: 20 PIV

#182 Bump to v1.1.1 + Update Changelog
  changelog.md
  package-lock.json
  package.json
Labels: Documentation, Enhancement

#185 Fix Stake rounding errors + improve Send GUI check
  scripts/transactions.js
Labels: Bug

#184 Contacts Implementation
  assets/style/style.css
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/contacts-book.js
  scripts/database.js
  scripts/global.js
  scripts/i18n.js
  scripts/index.js
  scripts/misc.js
  scripts/network.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 50 PIV

#162 Fix ledger xpub
  scripts/wallet.js
Labels: Bug, Enhancement

#186 Improve i18n utility, add English fallbacks
  scripts/contacts-book.js
  scripts/global.js
  scripts/i18n.js
  scripts/misc.js
  scripts/network.js
  scripts/promos.js
  scripts/scanner.js
  scripts/settings.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Bug, Enhancement, Awaiting Review, Review Reward: 20 PIV

#188 Improve CoinGecko stability, add attribution
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/prices.js
  scripts/settings.js
Labels: Bug, Enhancement, Awaiting Review, Review Reward: 10 PIV
