Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-05, with the labels that each got.

#115 New 'Staking' and small other changes
  assets/style/style.css
  index.template.html
  scripts/global.js
  scripts/network.js
  scripts/transactions.js
Labels: enhancement, High Priority (>1200 PIV)

#126 Fix multiple annoying UI exceptions
  scripts/global.js
  scripts/scanner.js
Labels: enhancement

#128 Fix lint errors
  .eslintrc.js
  scripts/global.js
  scripts/transactions.js
Labels: enhancement

#129 Fix CoinGecko spam (finally)
  scripts/global.js
  scripts/settings.js
  scripts/wallet.js
Labels: bug

#132 Resolve potential xss
  scripts/global.js
Labels: bug

#121 Switch to IndexedDb
  package-lock.json
  package.json
  scripts/chain_params.js
  scripts/charting.js
  scripts/database.js
  scripts/global.js
  scripts/i18n.js
  scripts/mempool.js
  scripts/settings.js
  scripts/transactions.js
  scripts/wallet.js
Labels: enhancement

#133 Change localStorage->database
  scripts/global.js
Labels: bug

#131 Implement Dashboard Activity
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/network.js
  scripts/settings.js
Labels: enhancement
