Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-04, with the labels that each got.

#111 Fix missing image metadata (Add three slashes)
  index.template.html
Labels: bug

#108 Various import fixes
  scripts/global.js
  scripts/index.js
  scripts/misc.js
  scripts/wallet.js
Labels: bug, documentation, enhancement

#106 Add QR support + BIP21
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  package-lock.json
  package.json
  scripts/chain_params.js
  scripts/global.js
  scripts/index.js
  scripts/misc.js
  scripts/scanner.js
Labels: enhancement

#112 Host all files internally
  assets/img_governance.png
  assets/img_pos.png
  assets/img_privacy.png
  assets/img_slider_bars.png
  assets/style/style.css
  index.template.html
  package-lock.json
  package.json
  scripts/global.js
  scripts/index.js
Labels: enhancement

#116 Add duddino explorer
  scripts/chain_params.js
Labels: enhancement

#91 Add ledger support to masternodes
  scripts/global.js
  scripts/masternode.js
  scripts/wallet.js
Labels: enhancement

#114 Add Balance Breakdown
  assets/style/style.css
  index.template.html
  package-lock.json
  package.json
  scripts/charting.js
  scripts/global.js
  scripts/index.js
Labels: enhancement

#113 Store votes and update governance tab
  assets/style/style.css
  scripts/global.js
  scripts/masternode.js
Labels: enhancement

#122 Handle exceptions
  scripts/charting.js
  scripts/global.js
  scripts/wallet.js
Labels: enhancement
