Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-09, with the labels that each got.

#190 Clarify Dashboard Send/Receive flows
  assets/style/style.css
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#189 Improve Mnemonic handling + UX, Add Advanced Mode
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/fr/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/settings.js
  scripts/wallet.js
Labels: Bug, Enhancement, Awaiting Review, Review Reward: 50 PIV

#192 Track Stake inputs for post-stake invalidation
  scripts/mempool.js
  scripts/network.js
Labels: Bug, Enhancement, Awaiting Review, Review Reward: 20 PIV

#194 Skip empty DB keys to prevent console spam
  scripts/database.js
Labels: Enhancement

#191 Italian translation
  locale/it/translation.js
  scripts/i18n.js
Labels: Enhancement, Low Priority (~135 PIV)

#193 Finalise translations for v1.2.0
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/contacts-book.js
  scripts/i18n.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#195 v1.2.0 bump + Update Changelog
  assets/style/style.css
  changelog.md
  package-lock.json
  package.json
  scripts/transactions.js
Labels: Documentation, Enhancement, Awaiting Review, Review Reward: 20 PIV

#196 Add full JSDoc context and types to translation global
  locale/template/translation.js
  scripts/i18n.js
Labels: Documentation

#198 Improve Governance consensus rules
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/chain_params.js
  scripts/global.js
Labels: Bug, Enhancement

#197 [Refactor] Decouple the wallet class
  index.template.html
  scripts/bitTrx.js
  scripts/contacts-book.js
  scripts/encoding.js
  scripts/global.js
  scripts/i18n.js
  scripts/index.js
  scripts/ledger.js
  scripts/masterkey.js
  scripts/masternode.js
  scripts/network.js
  scripts/promos.js
  scripts/settings.js
  scripts/transactions.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#158 Rewrite activity in vue
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  package-lock.json
  package.json
  scripts/Activity.vue
  scripts/global.js
  scripts/i18n.js
  scripts/index.js
  scripts/network.js
  scripts/settings.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#200 [Refactor] Clean up wallet related code
  index.template.html
  scripts/contacts-book.js
  scripts/global.js
  scripts/index.js
  scripts/masterkey.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: Enhancement

#205 Fix MasterKey use after #158 and #200 conflict
  scripts/Activity.vue
Labels: Bug

#207 Fix incorrect `getXPub` in `openExplorer()`
  scripts/global.js
Labels: Bug

#209 Solve activity spam
  scripts/global.js
  scripts/network.js
Labels: Bug, Awaiting Review

#208 Include also the last index in isOwnAddress
  scripts/wallet.js
Labels: Bug

#214 Load languages lazily
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/i18n.js
Labels: Enhancement

#217 Fix UI error upon receiving MN Collateral
  scripts/global.js
Labels: Bug
