Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-02, with the labels that each got.

#78 Docker image CI FIX
  .github/workflows/build.yaml
  docker/Dockerfile
Labels: enhancement

#73 New dashboard design and responsive!
  assets/key.png
  assets/pivx.png
  assets/style/style.css
  index.template.html
  package-lock.json
  package.json
  scripts/global.js
  scripts/index.js
  scripts/misc.js
  scripts/wallet.js
  webpack.config.js
Labels: enhancement, High Priority (>1200 PIV)

#79 Fix web metadata
  index.template.html
  webpack.config.js
Labels: bug, enhancement, Minor (~45 PIV)

#82 Simplify primary app text UI
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
Labels: enhancement

#83 Switch Google Fonts to Bunny.net
  assets/style/style.css
  index.template.html
Labels: enhancement

#85 Remove Donation System
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/chain_params.js
  scripts/index.js
  scripts/network.js
Labels: enhancement

#81 Prices + CoinGecko integration
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/misc.js
  scripts/prices.js
  scripts/settings.js
  scripts/wallet.js
Labels: enhancement

#84 Add Contested Proposals filtering
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/masternode.js
  scripts/network.js
Labels: enhancement

#86 Add date-commit hash as a tag to images
  .github/workflows/build.yaml
Labels: enhancement, Minor (~45 PIV)
