Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-11, with the labels that each got.

#245 Fix txdb not deleting testnet txs
  scripts/dashboard/Dashboard.vue
Labels: Bug

#241 I18n tools
  .gitignore
  locale/de/translation.js
  locale/de/translation.toml
  locale/en/translation.js
  locale/en/translation.toml
  locale/es-mx/translation.js
  locale/es-mx/translation.toml
  locale/fr/translation.js
  locale/fr/translation.toml
  locale/it/translation.js
  locale/it/translation.toml
  locale/lang-tools/add_string.py
  locale/lang-tools/comment_langs.py
  locale/lang-tools/lang_common.py
  locale/lang-tools/merge.py
  locale/lang-tools/requirements.txt
  locale/lang-tools/update_translations.py
  locale/nl/translation.js
  locale/nl/translation.toml
  locale/ph/translation.js
  locale/ph/translation.toml
  locale/pt-br/translation.js
  locale/pt-br/translation.toml
  locale/pt-pt/translation.js
  locale/pt-pt/translation.toml
  locale/pt/translation.toml
  locale/template/translation.js
  locale/template/translation.toml
  locale/uwu/translation.js
  locale/uwu/translation.toml
  package-lock.json
  package.json
  scripts/i18n.js
  scripts/settings.js
  tests/unit/masterkey.spec.js
  webpack.common.js
Labels: Enhancement

#251 Updating german translation
  locale/de/translation.toml
Labels: Enhancement

#248 Fix Changepassword and refactor
  scripts/aes-gcm.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/GenKeyWarning.vue
  scripts/wallet.js
Labels: Bug

#252 [Network] Do not set fullSync after reading txdb
  scripts/dashboard/Dashboard.vue
  scripts/mempool.js
  scripts/network.js
Labels: Bug

#253 [i18] fix alerts
  scripts/dashboard/CreateWallet.vue
  scripts/i18n.js
  scripts/settings.js
Labels: Bug

#247 Fix Lock and Unlock system
  scripts/dashboard/Dashboard.vue
  scripts/global.js
  scripts/index.js
  scripts/wallet.js
Labels: Bug, Enhancement

#257 Fix Double sync
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/dashboard/Dashboard.vue
  scripts/settings.js
Labels: Bug

#254 i18n Modal Fixes
  index.template.html
  scripts/dashboard/CreateWallet.vue
  scripts/dashboard/GenKeyWarning.vue
  scripts/i18n.js
Labels: Bug

#249 Bump to v1.4.0
  assets/style/style.css
  changelog.md
  locale/de/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/pt/translation.toml
  package-lock.json
  package.json
  scripts/i18n.js
Labels: Documentation, Enhancement, Awaiting Review, Review Reward: 50 PIV

#246 Change address v2
  scripts/global.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#265 Fix wallet not loading when explorer request fails
  scripts/global.js
Labels: Bug

#255 Auto detect currency
  package-lock.json
  package.json
  scripts/settings.js
  tests/unit/masterkey.spec.js
Labels: Enhancement

#269 [Wallet] Simplify importWallet flow
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/dashboard/Dashboard.vue
  scripts/wallet.js
Labels: Enhancement

#271 Refactor Dashboard with useWallet and useSettings composables
  scripts/composables/use_settings.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/wallet.js
Labels: refactor
