Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-10, with the labels that each got.

#220 Add duddino testnet explorer
  scripts/chain_params.js
Labels: Enhancement

#204 Wallet Balance GUI
  index.template.html
  scripts/WalletBalance.vue
  scripts/chain_params.js
  scripts/global.js
  scripts/mempool.js
  scripts/prices.js
  scripts/settings.js
  scripts/wallet.js
Labels: Enhancement

#222 Restore identicon to their former beauty
  scripts/WalletBalance.vue
Labels: Bug

#218 Ledger refactor
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/ledger.js
  scripts/masterkey.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Bug, Enhancement

#201 [Mempool] Mempool V2
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  package-lock.json
  package.json
  scripts/Activity.vue
  scripts/WalletBalance.vue
  scripts/bitTrx.js
  scripts/charting.js
  scripts/global.js
  scripts/mempool.js
  scripts/network.js
  scripts/promos.js
  scripts/script.js
  scripts/settings.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#216 jest
  .babelrc
  .github/workflows/lint.yaml
  jest.config.js
  package-lock.json
  package.json
  tests/unit/masterkey.spec.js
Labels: Documentation, Enhancement

#234 Ignore immature txs
  scripts/Activity.vue
  scripts/chain_params.js
  scripts/mempool.js
Labels: Bug, Enhancement

#231 Add full Base58Check validation (Standard + Cold)
  scripts/chain_params.js
  scripts/encoding.js
  scripts/misc.js
  tests/unit/masterkey.spec.js
Labels: Bug, Enhancement

#239 Fix lint not working for forks
  .github/workflows/lint.yaml
Labels: Bug

#233 Coin Lock system
  scripts/charting.js
  scripts/database.js
  scripts/global.js
  scripts/mempool.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Enhancement

#240 Fix German Activity
  locale/de/translation.js
Labels: Bug, Enhancement

#237 Ignore test directory in eslint
  .eslintrc.json
  package.json
Labels: Bug

#219 [Network] New Network model
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/nl/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/Activity.vue
  scripts/WalletBalance.vue
  scripts/global.js
  scripts/masterkey.js
  scripts/mempool.js
  scripts/network.js
  scripts/script.js
  scripts/settings.js
  scripts/transactions.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#235 Transaction Database
  scripts/database.js
  scripts/global.js
  scripts/mempool.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#232 Add logout button and encourage encryption
  index.template.html
  locale/de/translation.js
  locale/en/translation.js
  locale/es-mx/translation.js
  locale/fr/translation.js
  locale/it/translation.js
  locale/ph/translation.js
  locale/pt-br/translation.js
  locale/pt-pt/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/mempool.js
  scripts/settings.js
  scripts/wallet.js
Labels: Enhancement

#225 Rewrite the entire dashboard tab in vue
  assets/coin_plant.svg
  assets/fire.svg
  assets/p_logo.svg
  assets/phone.svg
  assets/style/style.css
  index.template.html
  package-lock.json
  package.json
  scripts/Modal.vue
  scripts/charting.js
  scripts/contacts-book.js
  scripts/dashboard/AccessWallet.vue
  scripts/dashboard/Activity.vue
  scripts/dashboard/CreateWallet.vue
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/ExportPrivKey.vue
  scripts/dashboard/GenKeyWarning.vue
  scripts/dashboard/Login.vue
  scripts/dashboard/TransferMenu.vue
  scripts/dashboard/VanityGen.vue
  scripts/dashboard/WalletBalance.vue
  scripts/encoding.js
  scripts/global.js
  scripts/i18n.js
  scripts/index.js
  scripts/ledger.js
  scripts/mempool.js
  scripts/misc.js
  scripts/network.js
  scripts/promos.js
  scripts/scanner.js
  scripts/settings.js
  scripts/transactions.js
  scripts/utils.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
  webpack.common.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV
