Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-03, with the labels that each got.

#88 Tidy up transaction.js
  package-lock.json
  scripts/transactions.js
Labels: documentation, enhancement

#87 Ledger fix
  index.template.html
  scripts/global.js
  scripts/wallet.js
Labels: bug, enhancement

#90 Added ipv6 support to masternodes
  package-lock.json
  package.json
  scripts/global.js
  scripts/masternode.js
Labels: enhancement

#94 Intro, navbar & footer improvements
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
Labels: enhancement

#89 New 'Transfer' design and small other changes
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/network.js
  scripts/transactions.js
Labels: enhancement, High Priority (>1200 PIV)

#98 Status Icons Redesign
  assets/style/style.css
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/network.js
  scripts/settings.js
Labels: enhancement

#93 Redesign wallet unlock flow
  scripts/global.js
  scripts/misc.js
  scripts/transactions.js
Labels: enhancement

#96 Performance and SEO optimisations
  assets/style/style.css
  index.template.html
  package-lock.json
  package.json
  scripts/bitTrx.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: enhancement

#101 Add View on Explorer button
  index.template.html
  scripts/global.js
  scripts/index.js
  scripts/wallet.js
Labels: enhancement

#102 Ran npm audit --fix
  package-lock.json
Labels: bug

#103 SEO and UX updates
  index.template.html
  locale/en/translation.js
  locale/template/translation.js
  locale/uwu/translation.js
  scripts/global.js
  scripts/index.js
  scripts/wallet.js
Labels: enhancement

#105 Fix typo
  scripts/network.js
  scripts/wallet.js
Labels: bug, enhancement

#99 Added proposal creation
  index.template.html
  scripts/bitTrx.js
  scripts/chain_params.js
  scripts/global.js
  scripts/index.js
  scripts/masternode.js
  scripts/network.js
  scripts/transactions.js
Labels: enhancement
