Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-01, with the labels that each got.

#69 [Docs] GitHub Pull Request guidelines
  .github/pull_request_template.md
Labels: documentation

#67 Modernise some alerts
  index.html
  scripts/masternode.js
  scripts/misc.js
Labels: bug, enhancement, Low Priority (~135 PIV)

#70 Bump protocol
  index.html
  scripts/masternode.js
Labels: enhancement, Minor (~45 PIV)

#65 Switched to /utxo API
  index.html
  scripts/mempool.js
  scripts/network.js
Labels: enhancement, Mid Priority (~405 PIV)

#71 Modified PR template to include comments
  .github/pull_request_template.md
Labels: documentation, enhancement, Minor (~45 PIV)

#68 Switch to webpack
  .eslintrc.js
  .gitignore
  .prettierrc.json
  assets/bootstrap-4.5.0/css/bootstrap.min.css
  assets/bootstrap-4.5.0/css/bootstrap.min.css.map
  assets/bootstrap-4.5.0/js/bootstrap.js
  assets/bootstrap-4.5.0/js/bootstrap.js.map
  assets/bootstrap-4.5.0/js/jquery.js
  docker/Dockerfile
  index.html
  index.template.html
  locale/en/translation.js
  locale/uwu/translation.js
  package-lock.json
  package.json
  scripts/aes-gcm.js
  scripts/bitTrx.js
  scripts/chain_params.js
  scripts/global.js
  scripts/i18n.js
  scripts/index.js
  scripts/libs/aes-gcm.js
  scripts/libs/bip39.js
  scripts/libs/bn.js
  scripts/libs/crypto-min.js
  scripts/libs/crypto-sha256-hmac.js
  scripts/libs/crypto-sha256.js
  scripts/libs/jdenticon.min.js
  scripts/libs/jsbn.js
  scripts/libs/ledger.js
  scripts/libs/noble-secp256k1.js
  scripts/libs/qrcode.js
  scripts/libs/ripemd160.js
  scripts/libs/script.js
  scripts/libs/sha256.js
  scripts/masternode.js
  scripts/mempool.js
  scripts/misc.js
  scripts/network.js
  scripts/script.js
  scripts/settings.js
  scripts/transactions.js
  scripts/utils.js
  scripts/vanitygen_worker.js
  scripts/wallet.js
  webpack.config.js
Labels: enhancement, High Priority (>1200 PIV)

#74 Fixed ledger not working
  locale/en/translation.js
  scripts/i18n.js
  scripts/transactions.js
  scripts/wallet.js
Labels: bug, enhancement, Mid Priority (~405 PIV)

#76 Implement PWA manifest, UI & service
  assets/icons/192.png
  assets/icons/512.png
  index.template.html
  manifest.json
  package.json
  scripts/global.js
  scripts/native-worker.js
  scripts/native.js
  webpack.config.js
Labels: enhancement
