Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2023-06, with the labels that each got.

#137 New 'Settings' page and indentation fix
  assets/style/style.css
  index.template.html
  scripts/global.js
  scripts/index.js
Labels: enhancement

#139 Implement app versioning, changelog & update popup
  assets/style/style.css
  changelog.md
  index.template.html
  scripts/changelog.js
  scripts/global.js
  scripts/index.js
  scripts/misc.js
  webpack.common.js
Labels: documentation, enhancement

#140 Improved Payment Requests
  scripts/global.js
  scripts/transactions.js
Labels: bug

#141 Activity Improvements
  scripts/global.js
  scripts/index.js
  scripts/network.js
  scripts/wallet.js
Labels: bug, enhancement

#142 Improve activity performance
  scripts/global.js
  scripts/transactions.js
  scripts/wallet.js
Labels: enhancement

#144 Add Explorer auto-switch (fallback mechanism)
  index.template.html
  scripts/global.js
  scripts/index.js
  scripts/network.js
  scripts/settings.js
Labels: enhancement

#147 [HTML+CSS] New Notifications
  assets/style/style.css
  scripts/misc.js
Labels: enhancement

#146 Add Cold Staking customisation UI
  index.template.html
  scripts/global.js
  scripts/index.js
  scripts/settings.js
  scripts/transactions.js
Labels: enhancement
