Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-11, with the labels that each got.

#431 Network Refactor
  scripts/dashboard/CreateWallet.vue
  scripts/dashboard/Dashboard.vue
  scripts/global.js
  scripts/index.js
  scripts/ledger.js
  scripts/legacy.js
  scripts/masternode.js
  scripts/network.js
  scripts/network/__mocks__/network_manager.js
  scripts/network/network.js
  scripts/network/network_manager.js
  scripts/promos.js
  scripts/settings.js
  scripts/stake/Stake.vue
  scripts/wallet.js
  tests/components/CreateWallet.test.js
  tests/integration/wallet/sync.spec.js
  tests/unit/use_wallet.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Refactor

#437 Make activity recognize proposal fees
  scripts/dashboard/Activity.vue
  scripts/historical_tx.js
  scripts/script.js
  scripts/transaction.js
  scripts/wallet.js
Labels: Enhancement

#448 Fix invalid password alerts
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/hi/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/alerts/alert.js
  scripts/dashboard/RestoreWallet.vue
Labels: Bug

#446 Fix wallet sync bug
  scripts/network/network.js
  scripts/wallet.js
Labels: Bug

#443 Faster wallet synchronization
  scripts/wallet.js
  tests/integration/wallet/sync.spec.js
Labels: Enhancement

#454 TransferMenu bug fixes and refactor
  scripts/composables/use_settings.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/TransferMenu.vue
  scripts/global.js
  scripts/prices.js
  scripts/settings.js
  tests/components/TransferMenu.test.js
Labels: Bug

#450 Convert to HistoricalTxs only once
  scripts/dashboard/Activity.vue
  scripts/historical_tx.js
  scripts/mempool.js
  scripts/wallet.js
Labels: Performance

#456 Remove global NetworkManager::callRPC
  scripts/global.js
  scripts/masternode.js
  scripts/network/network.js
  scripts/network/network_manager.js
Labels: Refactor

#438 Promo code Improvement
  assets/icons/icon-gift-opened.svg
  assets/style/style.css
  scripts/dashboard/Dashboard.vue
  scripts/global.js
  scripts/promos.js
Labels: Enhancement

#457 Randomize network selection
  scripts/settings.js
  scripts/utils.js
Labels: Enhancement

#449 Add cypress and basic commands
  .eslintrc.json
  .github/workflows/e2e.yaml
  .gitignore
  .prettierignore
  cypress.config.js
  cypress/E2E_TESTING_GUIDE.md
  cypress/e2e/wallet_balance.cy.js
  cypress/fixtures/e2e/wallet-balance-cy/wallet-balance-tests-calculates-balance-correctly.cy-playback
  cypress/snapshots/html/snapshot.html
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/support/snapshot.js
  index.template.html
  package-lock.json
  package.json
  scripts/alerts/Alert.vue
  scripts/dashboard/Activity.vue
  scripts/dashboard/WalletBalance.vue
Labels: Test

#459 Fix tests and add cy:record script
  cypress/E2E_TESTING_GUIDE.md
  cypress/e2e/wallet_balance.cy.js
  cypress/fixtures/e2e/wallet-balance-cy/wallet-balance-tests-calculates-balance-correctly.cy-playback
  cypress/snapshots/html/snapshot.html
  cypress/support/snapshot.js
  package.json
Labels: Test

#458 Ordered array
  scripts/ordered_array.js
  scripts/transaction.js
  scripts/utils.js
  scripts/wallet.js
  tests/unit/ordered_array.spec.js
Labels: Enhancement

#462 Update shield lib
  package-lock.json
  package.json
  scripts/wallet.js
Labels: Enhancement

#430 Add faster shield sync
  scripts/dashboard/WalletBalance.vue
  scripts/network/network.js
  scripts/network/network_manager.js
  scripts/transaction.js
  scripts/wallet.js
Labels: Enhancement

#464 More Activity bug fix and improvements
  scripts/dashboard/Activity.vue
  scripts/dashboard/Dashboard.vue
  scripts/stake/Stake.vue
  scripts/wallet.js
Labels: Enhancement

#466 Fix all linting warnings
  cypress.config.js
  scripts/chain_params.js
  scripts/database.js
  scripts/global.js
  scripts/network/__mocks__/network_manager.js
  scripts/network/network.js
  scripts/network/network_manager.js
  scripts/utils.js
  scripts/wallet.js
  tests/unit/start_batch.test.js
Labels: Cleanup

#465 Nicer Activity date format
  cypress/snapshots/html/snapshot.html
  scripts/dashboard/Activity.vue
Labels: Enhancement

#471 Add Reader class and refactor shield sync
  scripts/reader.js
  scripts/wallet.js
  tests/unit/reader.spec.js
Labels: Enhancement

#416 Shield Activity
  cypress/snapshots/html/snapshot.html
  scripts/dashboard/Activity.vue
  scripts/historical_tx.js
  scripts/mempool.js
  scripts/reader.js
  scripts/utils.js
  scripts/wallet.js
  tests/unit/mempool.spec.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#470 Fix address rotation
  scripts/composables/use_wallet.js
  scripts/global.js
  scripts/stake/Stake.vue
  scripts/wallet.js
  tests/integration/wallet/sync.spec.js
Labels: Bug

#476 fix unconfirmed activity bug
  scripts/wallet.js
Labels: Bug

#477 Integration test for getHistoricalTxs()
  tests/integration/wallet/sync.spec.js
Labels: Test

#468 Notification revamp
  assets/style/style.css
  scripts/alerts/Alert.vue
  scripts/alerts/Alerts.vue
  scripts/alerts/alert.js
  scripts/composables/use_alerts.js
  scripts/global.js
  tests/unit/alert.spec.js
Labels: Enhancement
