Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-09, with the labels that each got.

#385 Fix mode switching button showing on non-shield wallets
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/WalletBalance.vue
Labels: Bug

#388 Fix lockableFunction return type
  scripts/lock.js
Labels: Documentation, Trivial

#383 Add exchange address to activity & tests
  scripts/script.js
  scripts/wallet.js
  tests/unit/script.spec.js
Labels: Bug

#389 Remove unused analytics system
  assets/style/style.css
  index.template.html
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/hi/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/database.js
  scripts/global.js
  scripts/i18n.js
  scripts/network.js
  scripts/settings.js
Labels: Enhancement

#381 Add ledger persistance
  scripts/accounts.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/ledger.js
  scripts/masterkey.js
  tests/unit/use_wallet.spec.js
Labels: Enhancement

#394 Small fixes
  assets/style/style.css
  index.template.html
  scripts/changelog.js
  scripts/global.js
Labels: Enhancement

#393 Add in-modal address refresh + automatic type flipping
  scripts/composables/use_wallet.js
  scripts/contacts-book.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#390 Remove disconnection
  index.template.html
  scripts/SideNavbar.vue
  scripts/composables/use_settings.js
  scripts/global.js
  scripts/index.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: Enhancement, Awaiting Review, Review Reward: 20 PIV

#400 Trivial: remove unused function hasWalletUnlocked
  scripts/wallet.js
Labels: refactor

#399 Fix ledger masternodes
  scripts/global.js
Labels: Bug

#402 Custom EventEmitter
  scripts/event_bus.js
  scripts/mempool.js
  scripts/wallet.js
Labels: Enhancement

#398 v2.0 finalised
  assets/icons/icon-import.svg
  assets/style/style.css
  package-lock.json
  package.json
  scripts/dashboard/AccessWallet.vue
Labels: Awaiting Review, Review Reward: 50 PIV
