Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-10, with the labels that each got.

#408 Add unit test for EventEmitterWrapper
  tests/unit/event_bus.spec.js
Labels: Test

#405 Persistant Wallet Mode
  scripts/composables/use_wallet.js
  scripts/settings.js
Labels: Enhancement

#412 Potential bugs fix
  scripts/network.js
  scripts/wallet.js
Labels: Bug

#413 Faster TXDB Initialisation
  scripts/database.js
  scripts/transaction.js
Labels: Performance

#411 Migration Code Cleanup
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/hi/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/database.js
  scripts/settings.js
  tests/unit/database.spec.js
Labels: Cleanup

#407 Save shield during first sync
  scripts/wallet.js
Labels: Enhancement

#406 Fix Reward Aggregator
  scripts/dashboard/Activity.vue
Labels: Bug

#422 Catch cursor.continue() errors
  scripts/database.js
Labels: Bug

#424 Add automatic node switching
  scripts/global.js
  scripts/index.js
  scripts/masternode.js
  scripts/network.js
  scripts/settings.js
Labels: Enhancement

#423 Add AsyncInterval class
  scripts/async_interval.js
  scripts/global.js
  scripts/wallet.js
  tests/unit/wallet/signature.spec.js
  tests/utils/test_utils.js
Labels: Bug

#426 Remove console.logs
  .eslintrc.json
  debug_config.json
  scripts/__mocks__/network.js
  scripts/aes-gcm.js
  scripts/database.js
  scripts/debug.js
  scripts/global.js
  scripts/i18n.js
  scripts/ledger.js
  scripts/masternode.js
  scripts/native-worker.js
  scripts/network.js
  scripts/prices.js
  scripts/wallet.js
Labels: Enhancement

#429 Decouple Wallet and Network
  scripts/__mocks__/network.js
  scripts/dashboard/Activity.vue
  scripts/dashboard/WalletBalance.vue
  scripts/network.js
  scripts/wallet.js
Labels: Enhancement, Refactor

#428 Refactor some stuff
  scripts/composables/use_network.js
  scripts/dashboard/Activity.vue
  scripts/dashboard/WalletBalance.vue
  scripts/dashboard/WalletButtons.vue
  scripts/global.js
  scripts/historical_tx.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
Labels: Refactor

#425 Alert refactor
  index.template.html
  scripts/alerts/Alert.vue
  scripts/alerts/Alerts.vue
  scripts/alerts/alert.js
  scripts/composables/use_alerts.js
  scripts/contacts-book.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/GenKeyWarning.vue
  scripts/dashboard/RestoreWallet.vue
  scripts/dashboard/VanityGen.vue
  scripts/database.js
  scripts/global.js
  scripts/ledger.js
  scripts/legacy.js
  scripts/misc.js
  scripts/native.js
  scripts/network.js
  scripts/promos.js
  scripts/scanner.js
  scripts/settings.js
  scripts/stake/Stake.vue
  scripts/stake/StakeBalance.vue
  scripts/wallet.js
  tests/components/GenKeyWarning.test.js
  tests/components/StakeBalance.test.js
  tests/components/StakeInput.test.js
  tests/components/VanityGen.test.js
  tests/unit/alert.spec.js
  tests/unit/database.spec.js
  tests/unit/encoding.spec.js
Labels: Enhancement

#427 Add ability for MPW to run explorer-less
  scripts/dashboard/WalletBalance.vue
  scripts/network.js
  scripts/wallet.js
  tests/integration/wallet/sync.spec.js
Labels: Enhancement

#436 Actually call checkShieldSaplingRoot
  scripts/wallet.js
Labels: Bug

#432 Add duddino backup explorer
  chain_params.prod.json
Labels: Enhancement

#419 v2.0.1 finalised
  changelog.md
  package-lock.json
  package.json
  scripts/changelog.js
Labels: Documentation, Awaiting Review, Review Reward: 20 PIV

#440 doc: remove an unused portion of the PR template
  .github/pull_request_template.md
Labels: Documentation

#441 Fix activity time
  scripts/network.js
  scripts/wallet.js
Labels: Bug

#442 trivial: npm audit fix
  package-lock.json
Labels: Bug
