Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-02, with the labels that each got.

#244 Shield Support
  assets/shield_logo.svg
  assets/style/style.css
  chain_params.prod.json
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  netlify.toml
  package-lock.json
  package.json
  scripts/Loadingbar.vue
  scripts/__mocks__/global.js
  scripts/__mocks__/network.js
  scripts/accounts.js
  scripts/chain_params.js
  scripts/charting.js
  scripts/composables/use_wallet.js
  scripts/contacts-book.js
  scripts/dashboard/Activity.vue
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/TransferMenu.vue
  scripts/dashboard/WalletBalance.vue
  scripts/encoding.js
  scripts/global.js
  scripts/mempool.js
  scripts/misc.js
  scripts/native-worker.js
  scripts/network.js
  scripts/settings.js
  scripts/transaction.js
  scripts/transaction_builder.js
  scripts/utils.js
  scripts/wallet.js
  tests/components/TransferMenu.test.js
  tests/unit/start_batch.test.js
  tests/unit/transaction_builder.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
  webpack.dev.js
Labels: Enhancement, Awaiting Review, Review Reward: 50 PIV

#298 Remove rockdev explorer
  chain_params.prod.json
Labels: Bug

#299 Bump protocol version to 70927
  chain_params.prod.json
Labels: Consensus

#297 Add exchange address support
  chain_params.prod.json
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/dashboard/Dashboard.vue
  scripts/encoding.js
  scripts/misc.js
  scripts/script.js
  scripts/transaction_builder.js
  tests/unit/encoding.spec.js
  tests/unit/transaction_builder.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Enhancement

#301 Fix Masternode UTXO detection
  scripts/global.js
Labels: Bug

#295 Complete shield data in transaction class
  scripts/database.js
  scripts/transaction.js
  scripts/transaction_builder.js
  scripts/wallet.js
  tests/unit/transaction.spec.js
  tests/unit/transaction.test.json
  tests/unit/transaction_builder.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Enhancement

#300 v1.5.0 finalised
  changelog.md
  locale/it/translation.toml
  package-lock.json
  package.json
  scripts/dashboard/WalletBalance.vue
Labels: Documentation, Awaiting Review, Review Reward: 20 PIV

#309 Fix PIVX Promos text spacing
  scripts/dashboard/Dashboard.vue
Labels: Bug

#304 Fix negative numbmer value balances
  scripts/transaction.js
  tests/unit/transaction.spec.js
  tests/unit/transaction.test.json
Labels: Bug
