Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-04, with the labels that each got.

#332 Actually discard a transaction
  scripts/composables/use_wallet.js
  scripts/legacy.js
  scripts/wallet.js
Labels: Bug

#323 Network refactor
  scripts/__mocks__/network.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Activity.vue
  scripts/dashboard/Dashboard.vue
  scripts/global.js
  scripts/network.js
  scripts/settings.js
  scripts/wallet.js
  tests/unit/wallet/signature.spec.js
Labels: refactor

#339 Fix change passwd
  scripts/composables/use_wallet.js
  scripts/wallet.js
Labels: Bug, High Priority (>1200 PIV)

#340 Unify shield and transparent sync
  scripts/mempool.js
  scripts/network.js
  scripts/wallet.js
Labels: Enhancement

#325 Rewrite stake tab in vue
  index.template.html
  package-lock.json
  package.json
  scripts/BottomPopup.vue
  scripts/Modal.vue
  scripts/accounts.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/RestoreWallet.vue
  scripts/dashboard/TransferMenu.vue
  scripts/global.js
  scripts/index.js
  scripts/legacy.js
  scripts/network.js
  scripts/parsed_secret.js
  scripts/promos.js
  scripts/settings.js
  scripts/stake/Stake.vue
  scripts/stake/StakeBalance.vue
  scripts/stake/StakeInput.vue
  scripts/wallet.js
  tests/components/StakeBalance.test.js
  tests/components/StakeInput.test.js
Labels: Enhancement, Awaiting Review, Review Reward: 10 PIV

#344 avoid calling getBlockCount()
  scripts/__mocks__/global.js
  scripts/dashboard/Activity.vue
  scripts/global.js
  scripts/wallet.js
  tests/unit/wallet/signature.spec.js
Labels: Enhancement

#343 Speed up shield sync
  scripts/network.js
  scripts/wallet.js
Labels: Enhancement

#349 Remove the Refresh button
  assets/style/style.css
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/WalletBalance.vue
  scripts/global.js
  scripts/stake/StakeBalance.vue
Labels: Enhancement

#346 Fix Governance Dashboard display of Over-Allocated proposals
  assets/style/style.css
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/global.js
Labels: Bug

#347 Secret parsing tests
  tests/unit/parsed_secret.json
  tests/unit/parsed_secret.spec.js
Labels: Test

#352 Implement Oracle in replacement of CoinGecko
  index.template.html
  scripts/composables/use_wallet.js
  scripts/global.js
  scripts/prices.js
  scripts/settings.js
Labels: Enhancement

#355 Minimize countries.json
  webpack.common.js
Labels: Enhancement

#356 refactor price.js
  scripts/composables/use_wallet.js
  scripts/global.js
  scripts/prices.js
  scripts/settings.js
Labels: refactor

#362 test: remove mempool mocks
  scripts/__mocks__/mempool.js
  tests/unit/test_utils.js
  tests/unit/use_wallet.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Test
