Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-12, with the labels that each got.

#480 A couple of Wallet refactors
  scripts/wallet.js
Labels: Refactor

#483 Silence tests
  debug_config.json
  scripts/dashboard/VanityGen.vue
  scripts/debug.js
  test_setup.js
Labels: Cleanup

#486 v2.1 finalised
  assets/style/style.css
  changelog.md
  package-lock.json
  package.json
  scripts/changelog.js
Labels: Documentation, Awaiting Review, Review Reward: 50 PIV

#495 Fix all linting warnings
  scripts/global.js
Labels: Cleanup

#499 Change bytes to num function
  scripts/encoding.js
Labels: Bug

#501 Add privacy warning for XPub sharing
  scripts/contacts-book.js
Labels: Bug, Cleanup

#498 Various PIVX Promos fixes
  scripts/dashboard/Dashboard.vue
  scripts/promos.js
Labels: Bug

#497 Export Wallet fixes
  assets/style/style.css
  scripts/dashboard/ExportPrivKey.vue
Labels: Bug

#496 Fix Governance Budget + Superblock display on iOS Safari
  scripts/governance/Governance.vue
Labels: Bug

#504 Fix unstake auto unlock
  scripts/stake/Stake.vue
Labels: Bug

#502 v2.1.1 finalised
  changelog.md
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/fr/translation.toml
  locale/hi/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  package-lock.json
  package.json
  scripts/stake/Stake.vue
Labels: Documentation, Awaiting Review, Review Reward: 50 PIV
