Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-03, with the labels that each got.

#305 Refactor tx version
  scripts/chain_params.js
  scripts/transaction.js
  scripts/transaction_builder.js
  scripts/wallet.js
  tests/unit/transaction.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Bug, Enhancement

#310 Add temporary Pending Shield UI
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/WalletBalance.vue
Labels: Enhancement

#314 Fix progress bar
  scripts/Loadingbar.vue
Labels: Bug

#315 Handle shield tx creation errors
  scripts/dashboard/Dashboard.vue
  scripts/wallet.js
Labels: Bug

#311 Improve tx creation flow
  scripts/transaction.js
  scripts/transaction_builder.js
  scripts/wallet.js
  tests/unit/wallet/transactions.spec.js
Labels: Enhancement

#313 Update txid in fromHex
  scripts/transaction.js
Labels: Enhancement

#318 Add commit hash to dev builds
  package.json
  scripts/changelog.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: Enhancement

#317 Add an option to automatically lock the wallet
  index.template.html
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/composables/use_settings.js
  scripts/dashboard/Dashboard.vue
  scripts/global.js
  scripts/index.js
  scripts/settings.js
Labels: Enhancement

#291 Mempool refactor
  package.json
  scripts/__mocks__/global.js
  scripts/__mocks__/mempool.js
  scripts/charting.js
  scripts/composables/use_wallet.js
  scripts/dashboard/Activity.vue
  scripts/dashboard/Dashboard.vue
  scripts/database.js
  scripts/global.js
  scripts/historical_tx.js
  scripts/legacy.js
  scripts/mempool.js
  scripts/network.js
  scripts/transaction.js
  scripts/wallet.js
  tests/unit/mempool.spec.js
  tests/unit/transaction.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Awaiting Review, Review Reward: 20 PIV, refactor, Test

#319 Fix ledger masternode creation
  scripts/dashboard/Dashboard.vue
  scripts/masterkey.js
Labels: Bug

#326 Fix Payment Descriptions regression
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/TransferMenu.vue
Labels: Bug

#328 v1.5.1 finalised
  changelog.md
  package-lock.json
  package.json
Labels: Awaiting Review, Review Reward: 20 PIV
