Repository PIVX-Labs/MyPIVXWallet, pull requests merged in 2024-05, with the labels that each got.

#354 Shield fixes
  locale/cnr/translation.toml
  locale/de/translation.toml
  locale/en/translation.toml
  locale/es-mx/translation.toml
  locale/fr/translation.toml
  locale/it/translation.toml
  locale/nl/translation.toml
  locale/ph/translation.toml
  locale/pl/translation.toml
  locale/pt-br/translation.toml
  locale/pt-pt/translation.toml
  locale/template/translation.toml
  locale/uwu/translation.toml
  scripts/composables/use_wallet.js
  scripts/dashboard/Dashboard.vue
  scripts/dashboard/WalletBalance.vue
  scripts/global.js
  scripts/mempool.js
  scripts/stake/Stake.vue
  scripts/wallet.js
  tests/unit/test_utils.js
  tests/unit/use_wallet.spec.js
  tests/unit/wallet/transactions.spec.js
Labels: Bug, Enhancement

#363 Fix bunch of bugs
  scripts/dashboard/Dashboard.vue
  scripts/index.js
  scripts/mempool.js
  scripts/settings.js
  scripts/wallet.js
Labels: Bug

#359 Fix spending txs with shield data on ledger
  scripts/ledger.js
Labels: Bug

#342 Improve debug logs
  debug_config.json
  scripts/debug.js
  scripts/global.js
  scripts/network.js
Labels: Enhancement

#364 [TEST] Network simulator and some initial tests
  scripts/__mocks__/network.js
  scripts/global.js
  scripts/wallet.js
  tests/integration/wallet/sync.spec.js
  tests/unit/masterkey.spec.js
  tests/unit/test_utils.js
  tests/unit/use_wallet.spec.js
  tests/unit/wallet/signature.spec.js
  tests/unit/wallet/transactions.spec.js
  tests/utils/test_utils.js
Labels: Test

#366 Use country map json instead of the provided functions
  scripts/settings.js
Labels: Enhancement

#368 Fix undefined alerts when locale is missing
  scripts/i18n.js
  tests/unit/i18n.spec.js
Labels: Bug

#361 Fix Immature balance bug
  scripts/__mocks__/network.js
  scripts/mempool.js
  scripts/transaction.js
  scripts/wallet.js
  tests/integration/wallet/sync.spec.js
  tests/unit/mempool.spec.js
  tests/utils/test_utils.js
Labels: Bug
